
Title: Practical Machine Learning Course Project
========================================================

Project Introduction
------------

### Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

### Data
The training data for this project are available here:

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here:

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.

### Goal
The goal of your project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. You may use any of the other variables to predict with. You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases.

Getting and loading the data
----------------------------
```{r}
library(caret)
library(rpart)
library(rpart.plot)
library(RColorBrewer)
library(rattle)
library(randomForest)
library(knitr)

set.seed(12345)

trainUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl <- "http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

training <- read.csv(url(trainUrl), na.strings=c("NA","#DIV/0!",""))
testing <- read.csv(url(testUrl), na.strings=c("NA","#DIV/0!",""))
```

Creating a partition for the training set
```{r}
inTrain <- createDataPartition(training$classe, p=0.6, list=FALSE)
myTraining <- training[inTrain, ]
myTesting <- training[-inTrain, ]
dim(myTraining)
dim(myTesting)
```

Cleaning the data
-----------------

### Remove nearzero variance variables
```{r}
nzv <- nearZeroVar(myTraining, saveMetrics=TRUE)
myTraining <- myTraining[,nzv$nzv==FALSE]

nzv<- nearZeroVar(myTesting,saveMetrics=TRUE)
myTesting <- myTesting[,nzv$nzv==FALSE]
```
### Remove first column with cell number
myTraining <- myTraining[c(-1)]

### Remove variables with >70% missing/NA values
```{r}
training_noNA <- myTraining
for(i in 1:length(myTraining)) {
    if( sum( is.na( myTraining[, i] ) ) /nrow(myTraining) >= .7) {
        for(j in 1:length(training_noNA)) {
            if( length( grep(names(myTraining[i]), names(training_noNA)[j]) ) == 1)  {
                training_noNA <- training_noNA[ , -j]
            }   
        } 
    }
}

# Set back to the original variable name
myTraining <- training_noNA
rm(training_noNA)
```

### Transform the myTesting and testing data sets
```{r}
clean1 <- colnames(myTraining)
clean2 <- colnames(myTraining[, -58])  # remove the classe column
myTesting <- myTesting[clean1]        
testing <- testing[clean2]            

dim(myTesting)
dim(testing)
```

### Get the data in same type
```{r}
for (i in 1:length(testing) ) {
    for(j in 1:length(myTraining)) {
        if( length( grep(names(myTraining[j]), names(testing)[i]) ) == 1)  {
            class(testing[i]) <- class(myTraining[j])
        }      
    }      
}

# get the same type between testing and myTraining
testing <- rbind(myTraining[2, -58] , testing)
testing <- testing[-1,]
```

Prediction with Decision Trees
------------------------------
```{r}
set.seed(12345)
modFit1 <- rpart(classe ~ ., data=myTraining, method="class")
fancyRpartPlot(modFit1)

predictions1 <- predict(modFit1, myTesting, type = "class")
dectree <- confusionMatrix(predictions1, myTesting$classe)
dectree

plot(dectree$table, col = dectree$byClass, main = paste("Decision Tree Confusion Matrix: Accuracy =", round(dectree$overall['Accuracy'], 4)))

```

Predicting with Random Forests
------------------------------
```{r}
set.seed(12345)
modFit2 <- randomForest(classe ~ ., data=myTraining)
predictions2 <- predict(modFit2, myTesting, type = "class")
rf <- confusionMatrix(predictions2, myTesting$classe)
rf

plot(rf$table, col = rf$byClass, main = paste("Random Forest Confusion Matrix: Accuracy =", round(rf$overall['Accuracy'], 4)))

```

Decision trees give an accuracy of 87.89% on the test set, while Random Forests give a higher accuracy of 99.89% on the test set. Expected out of sample error is 100-99.89 = 0.11%

Predicting Results on the Test Data
-----------------------------------
```{r}
prediction_test <- predict(modFit2, testing, type = "class")
prediction_test
```


